"Allow all items to be added" = false
"Morph in the offhand instead of mainhand" = false
"Whitelisted Items" = ["compactmachines:personal_shrinking_device", "immersiveengineering:tool", "transport:rail_breaker", "storagedrawers:drawer_key", "resourcefulbees_scraper"]
"Whitelisted Names" = ["wrench", "screwdriver", "hammer", "rotator", "configurator", "crowbar"]
"Blacklisted Mods" = []
"Mod Aliases" = ["rsrequestify=refinedstorage", "framedcompactdrawers=storagedrawers", "extrastorage=refinedstorage", "thermalexpansion=thermalfoundation", "thermaldynamics=thermalfoundation", "thermalcultivation=thermalfoundation", "integrateddynamics=integratedtunnels", "mekanismgenerators=mekanism", "mekanismtools=mekanism", "xnet=rftoolsbase", "rftoolspower=rftoolsbase", "rftoolsutility=rftoolsbase", "rftoolsstorage=rftoolsbase", "rftoolscontrol=rftoolsbase", "rftoolsbuilder=rftoolsbase", "rftoolsdimensions=rftoolsbase"]

